---
# Query OpenStack Barbican to retrieve secret keys
# needed for a cluster deployment
- hosts: openstack
  roles:
    - role: alaska_secrets
      secret_name: "ceph.client.alaska.key"
      secret_var: "alaska_ceph_key"
  
# This playbook applies site config for Ceph client support,
# in particular CephFS home directories
- hosts: cluster_ceph_client
  remote_user: centos
  become: yes
  roles:
    - role: ceph_setup
      ceph_client: alaska
      ceph_secret: "{{ hostvars['localhost']['alaska_ceph_key'] }}"
    - role: ceph_homedir
      homedir_client: alaska
      homedir_path: "{{ alaska_homedir }}"
      homedir_server: "{{ alaska_softiron }}:6789"
