---
- name: Intiate reboot
  command: "/usr/sbin/shutdown -r +1"
  become: True

- name: Ensure the node goes down
  local_action:
    module: wait_for
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: 22
    state: stopped
    timeout: "{{ reboot_down_timeout }}"

- name: Wait for SSH access to return
  local_action:
    module: wait_for
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: 22
    state: started
    timeout: "{{ reboot_up_timeout }}"
